### ISSUE TITLE
Please expedite current pull request and send to PSGallery

### ISSUE THREAD

**Issue by theJasonHelmick** [PowerShell/xAdcsDeployment#22]
The changes in the new pull request are greatly needed if there is anyway to expedite -- and get into a new version in PSGallery.   Sorry for the request, I know everyone is busy ..... just need this for production.

**Comment by PlagueHO** [comment]
I wish I could help get this through quicker, but I think the DSC team are pretty snowed under. I think they may done a really long few days/nights getting the new [PSDscResources](https://github.com/PowerShell/PSDscResources) module out the door in time for WS2016 GA.  @kwirkykat - not sure if there is anything you or your team can do?

**Comment by theJasonHelmick** [comment]
Actually -- I might be able to get some help from the DSC team.  I'll email Joey today and see if we cn move this along.  Cheers!

**Comment by mbreakey3** [comment]
@theJasonHelmick - Which PR is it? I can look into it

**Comment by mbreakey3** [comment]
Nevermind, just found it. Closing this issue
