### ISSUE TITLE
Module contains two copies of all resoruces

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xAdcsDeployment#6]
This resource module seems to contains two copies of the DSC Resources:
https://github.com/PowerShell/xAdcsDeployment/tree/dev/DSCResources
https://github.com/PowerShell/xAdcsDeployment/tree/dev/xCertificateServices/DSCResources

This means that whenever changes need to be made (or additional features added) to this DSC module, it needs to be made in two locations. This could potentially lead to mismatches and other problems.

Is there a reason for this double up of resources?

Is it possible to remove the xCertificateServices folder from this repo?

**Comment by PlagueHO** [comment]
@TravisEz13 - do you have any feelings on this one? I'd like to get rid of this legacy xCertificateServices folder as it is not a good idea to have two copies of all resources.

**Comment by TravisEz13** [comment]
I agree the legacy one /tree/dev/xCertificateServices/DSCResources is likely not used.
