### ISSUE TITLE
Bug in example file of xAdcsDeployment

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xAdcsDeployment#9]
Within the example folder in the .ps1 file: Config-SetupActiveDirectory.ps1

line 110: imports xCertificateServices which is a sub module of the current module (xAdcsDeplyment) so it can't find it unless the xCertificateServices folder is copied into the program modules folder on the local machine.

line 114/120: xWaitForDisk and xDisk - not entirely sure if this is a bug, but it looks like the module xDisk which is where both of these come from has been replaced by xStorage.

**Comment by PlagueHO** [comment]
@mbreakey3 - You're quite right - good catch.

This entire folder should also be moved into the Root of the repo as well as the xCertificateServices folder should be deleted (see issue #6).

Do you want to PR it or shall I?
